#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_dark_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_light_background = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_shadow_end_color = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int cardview_shadow_start_color = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int colorPrimary = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int colorPrimaryLight = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int colorSecondary = 2131230726;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int cardview_compat_inset_shadow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int cardview_default_elevation = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cardview_default_radius = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int item_touch_helper_swipe_escape_velocity = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Fishlet = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SireaFish = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060039
			public const int AnomaliesEntered = 2131099705;
			
			// aapt resource value: 0x7f060036
			public const int BackSpineChosen = 2131099702;
			
			// aapt resource value: 0x7f060034
			public const int BodyShapeChosen = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int FamilyPredicted = 2131099698;
			
			// aapt resource value: 0x7f060038
			public const int LengthChosen = 2131099704;
			
			// aapt resource value: 0x7f06003a
			public const int LocationChosen = 2131099706;
			
			// aapt resource value: 0x7f060035
			public const int MouthShapeChosen = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int TailShapeChosen = 2131099703;
			
			// aapt resource value: 0x7f060005
			public const int additional_content = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int camera_preview = 2131099654;
			
			// aapt resource value: 0x7f060028
			public const int checkBoxBackSpineLayout = 2131099688;
			
			// aapt resource value: 0x7f06000b
			public const int checkBoxBodyLayout = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int checkBoxLength = 2131099665;
			
			// aapt resource value: 0x7f06001a
			public const int checkBoxMouthLayout = 2131099674;
			
			// aapt resource value: 0x7f060021
			public const int checkBoxTailLayout = 2131099681;
			
			// aapt resource value: 0x7f06000e
			public const int checkbox_Compressed = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int checkbox_Depressed = 2131099660;
			
			// aapt resource value: 0x7f06001d
			public const int checkbox_Dorsal = 2131099677;
			
			// aapt resource value: 0x7f06002a
			public const int checkbox_Dorsal_Spine = 2131099690;
			
			// aapt resource value: 0x7f06000d
			public const int checkbox_Elongated = 2131099661;
			
			// aapt resource value: 0x7f060025
			public const int checkbox_Emarginate = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int checkbox_Forked = 2131099683;
			
			// aapt resource value: 0x7f06000f
			public const int checkbox_Fusiform = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int checkbox_Inferior = 2131099675;
			
			// aapt resource value: 0x7f06002d
			public const int checkbox_Long_dorsal_spine = 2131099693;
			
			// aapt resource value: 0x7f060029
			public const int checkbox_None = 2131099689;
			
			// aapt resource value: 0x7f060022
			public const int checkbox_Pointed = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int checkbox_Rounded = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int checkbox_Semi_Truncate = 2131099686;
			
			// aapt resource value: 0x7f06002b
			public const int checkbox_Serrated = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int checkbox_Short_dorsal_spine = 2131099692;
			
			// aapt resource value: 0x7f06001f
			public const int checkbox_Sub_Terminal = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int checkbox_Terminal = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int checkbox_Upturned = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int edit_toolbar_additional = 2131099655;
			
			// aapt resource value: 0x7f06002f
			public const int edit_toolbar_main = 2131099695;
			
			// aapt resource value: 0x7f06003b
			public const int fish_image = 2131099707;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int length0 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int length1 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int length2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int length3 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int length4 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int length5 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int length6 = 2131099672;
			
			// aapt resource value: 0x7f06002e
			public const int main_content = 2131099694;
			
			// aapt resource value: 0x7f06003e
			public const int menu_camera = 2131099710;
			
			// aapt resource value: 0x7f06003d
			public const int menu_continue = 2131099709;
			
			// aapt resource value: 0x7f060031
			public const int possible_matchings = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int possible_matchings_text = 2131099699;
			
			// aapt resource value: 0x7f060027
			public const int promptBackSpine = 2131099687;
			
			// aapt resource value: 0x7f06000a
			public const int promptBody = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int promptLength = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int promptMouth = 2131099673;
			
			// aapt resource value: 0x7f060020
			public const int promptTail = 2131099680;
			
			// aapt resource value: 0x7f060004
			public const int text_anomalies = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int text_image = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int toolbar_additional = 2131099649;
			
			// aapt resource value: 0x7f06003c
			public const int toolbar_bottom_possibleMatchings = 2131099708;
			
			// aapt resource value: 0x7f060008
			public const int toolbar_main = 2131099656;
			
			// aapt resource value: 0x7f060030
			public const int toolbar_top_possibleMatchings = 2131099696;
			
			// aapt resource value: 0x7f060002
			public const int txtFish_Additional_Details = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int txtFish_Description = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AdditionalDetails = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PossibleMatchings = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int bottom_menu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int edit_menus = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int possible_matchings_menu = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int back = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int camera = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int continue1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_action_content_create = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_action_content_save = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_menu_copy_holo_dark = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_menu_cut_holo_dark = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ic_menu_paste_holo_dark = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ic_menu_search_holo_dark = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int map = 2130903049;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int additional_details = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int describe_the_fish = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int possible_matchings = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int promptBackSpine = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int promptBody = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int promptBodyLength = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int promptMouth = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int promptTail = 2131296263;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MyTheme = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
